;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/StationTimetable/Content/Localization/StationTimetable
DestinationPath=Mods/GameFeatures/StationTimetable/Content/Localization/StationTimetable
ManifestName=StationTimetable.manifest
ArchiveName=StationTimetable.archive
PortableObjectName=StationTimetable.po
ResourceName=StationTimetable.locres
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=de

[GatherTextStep0]
CommandletClass=InternationalizationExport
bImportLoc=true

[GatherTextStep1]
CommandletClass=GenerateTextLocalizationResource

